## Resources

In [12]:
import gymnasium as gym
import numpy as np


def policy_evaluation(env, policy, gamma=0.9, theta=0.0001):

    n_states = env.observation_space.n
    V = np.zeros(n_states)

    while True:

        delta = 0

        for state in range(n_states):

            action = policy[state]

            value = 0

            for probability, next_state, reward, terminated in env.unwrapped.P[state][action]:

                if terminated:
                    value += probability * reward
                else:
                    value += probability * (
                        reward + gamma * V[next_state]
                    )

            delta = max(delta, abs(V[state] - value))

            V[state] = value

        if delta < theta:
            break

    return V


def policy_improvement(env, V, gamma=0.9):

    n_states = env.observation_space.n
    n_actions = env.action_space.n

    new_policy = np.zeros(n_states, dtype=int)

    for state in range(n_states):

        action_values = np.zeros(n_actions)

        for action in range(n_actions):

            for probability, next_state, reward, terminated in env.unwrapped.P[state][action]:

                if terminated:
                    action_values[action] += probability * reward
                else:
                    action_values[action] += probability * (
                        reward + gamma * V[next_state]
                    )

        new_policy[state] = np.argmax(action_values)

    return new_policy


def display_policy(policy):

    action_symbols = {
        0: "←",
        1: "↓",
        2: "→",
        3: "↑"
    }

    policy_grid = []

    for row in range(4):

        row_policy = []

        for col in range(4):

            state = row * 4 + col

            row_policy.append(action_symbols[policy[state]])

        policy_grid.append(row_policy)

    print(np.array(policy_grid))


def policy_iteration(env, gamma=0.9):

    n_states = env.observation_space.n

    policy = np.zeros(n_states, dtype=int)

    iteration = 0

    while True:

        iteration += 1

        V = policy_evaluation(
            env,
            policy,
            gamma
        )

        new_policy = policy_improvement(
            env,
            V,
            gamma
        )

        print("Optimal State-Value Function:")
        print(np.round(V.reshape(4, 4), 4))

        print("\nOptimal Policy:")
        display_policy(new_policy)

        print("\nPolicy iterations:", iteration)
        print("----------------------------------------")

        if np.array_equal(policy, new_policy):

            policy = new_policy

            break

        policy = new_policy

    return V, policy, iteration


env = gym.make(
    "FrozenLake-v1",
    map_name="4x4",
    is_slippery=True
)

V, policy, iterations = policy_iteration(
    env,
    gamma=0.9
)

print("\nAfter Policy Iteration :")
print("----------------------------------------")

print("Optimal State-Value Function:")
print(np.round(V.reshape(4, 4), 4))

print("\nOptimal Policy:")
display_policy(policy)

print("\nPolicy iterations:", iterations)

print("\nName : Vikamuhan N")
print("Register Number : 212223240181")

env.close()

Optimal State-Value Function:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Optimal Policy:
[['←' '←' '←' '←']
 ['←' '←' '←' '←']
 ['←' '←' '←' '←']
 ['←' '←' '↓' '←']]

Policy iterations: 1
----------------------------------------
Optimal State-Value Function:
[[0.     0.     0.0234 0.01  ]
 [0.     0.     0.0548 0.    ]
 [0.     0.     0.1593 0.    ]
 [0.     0.     0.4762 0.    ]]

Optimal Policy:
[['←' '↓' '→' '↑']
 ['←' '←' '←' '←']
 ['←' '↓' '←' '←']
 ['←' '↓' '→' '←']]

Policy iterations: 2
----------------------------------------
Optimal State-Value Function:
[[0.     0.0172 0.0573 0.0429]
 [0.     0.     0.0912 0.    ]
 [0.     0.1488 0.2465 0.    ]
 [0.     0.2494 0.5818 0.    ]]

Optimal Policy:
[['↓' '↑' '→' '↑']
 ['←' '←' '←' '←']
 ['↓' '↓' '←' '←']
 ['←' '→' '↓' '←']]

Policy iterations: 3
----------------------------------------
Optimal State-Value Function:
[[0.0477 0.0494 0.0677 0.0506]
 [0.0621 0.     0.1075 0.    ]
 [0.0974 0.2272 0.2908 0.    ]
 [0. 